[consensus_config]
max_message_len = 1048576
peers_timeout = 10000
round_timeout = 3000
status_timeout = 5000
txs_block_limit = 1000

[consensus_config.timeout_adjuster]
timeout = 500
type = "Constant"

[general_config]
validators_count = 4

[services_config]
