[common.consensus_config]
max_message_len = 1048576
peers_timeout = 10000
round_timeout = 3000
status_timeout = 5000
txs_block_limit = 1000

[common.consensus_config.timeout_adjuster]
timeout = 500
type = "Constant"

[common.general_config]
validators_count = 4

[common.services_config]

[node]
addr = "127.0.0.1:6332"

[node.services_public_configs]

[node.validator_keys]
consensus_key = "b1501c1392e70a5b63a802881b7b4fabf08586d868354abd12f5c066bb05d756"
service_key = "75e153b778bcf3b04e4a941a6662704dd4ab2f53121238ade7eee2a9e0906c2d"
